apiVersion: v1
kind: Secret
metadata:
  name: gateway-secret
  namespace: interview-hub-ns1
type: Opaque
stringData:
  JWT_SIGNING_SECRET: "<your-jwt-signing-secret>"
---
apiVersion: v1
kind: Secret
metadata:
  name: core-secret
  namespace: interview-hub-ns1
type: Opaque
stringData:
  DB_URL: "<jdbc:postgresql://...>"
  DB_USERNAME: "<db-username>"
  DB_PASSWORD: "<db-password>"
  GOOGLE_CLIENT_ID: "<google-client-id>"
  GOOGLE_CLIENT_SECRET: "<google-client-secret>"
  JWT_SIGNING_SECRET: "<your-jwt-signing-secret>"
  RABBITMQ_URL: "<amqps://...@cloudamqp-host/vhost>"
---
apiVersion: v1
kind: Secret
metadata:
  name: calendar-secret
  namespace: interview-hub-ns1
type: Opaque
stringData:
  GOOGLE_CLIENT_ID: "<google-client-id>"
  GOOGLE_CLIENT_SECRET: "<google-client-secret>"
  GOOGLE_CALENDAR_ID: "<calendar-id-or-primary>"
  GOOGLE_CALENDAR_REFRESH_TOKEN: "<refresh-token>"
---
apiVersion: v1
kind: Secret
metadata:
  name: notification-secret
  namespace: interview-hub-ns1
type: Opaque
stringData:
  RESEND_API_KEY: "<resend-api-key>"
  RABBITMQ_URL: "<amqps://...@cloudamqp-host/vhost>"
  MAIL_FROM: "<noreply@lcarera.dev>"
  FRONTEND_URL: "http://interview-hub.local"
