apiVersion: v1
kind: ServiceAccount
metadata:
  name: gateway-sa
  namespace: interview-hub-ns1
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: backend-sa
  namespace: interview-hub-ns1
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: calendar-sa
  namespace: interview-hub-ns1
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: notification-sa
  namespace: interview-hub-ns1
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: frontend-sa
  namespace: interview-hub-ns1
